### ISSUE TITLE
Node v16 actions are deprecated

### ISSUE THREAD

**Issue by chrisnruud** [Azure/aks-set-context#106]
Bump action to node v20 to be compatible with current github platform

**Comment by spkane** [comment]
cc/ @manidharanupoju24 And one more action that will need updating in our workflows when it has been upgraded with a Node 20 version.

**Comment by davidgamero** [comment]
should be addressed with a new release when #100 merges

**Comment by chrisnruud** [comment]
Any news on release schedule?

**Comment by aloknecessary** [comment]
Hi, when will this get merged?

**Comment by davidgamero** [comment]
update: the release is now complete
