### ISSUE TITLE
Hard coded URLs in login.ts

### ISSUE THREAD

**Issue by ammohant** [Azure/aks-set-context#12]
Can we please fix the hard coded URLs liek the following ? They will have issues when we move to more generic cloud  support. 
const managementEndpointUrl = 'https://management.azure.com/'

**Comment by ds-ms** [comment]
@ammohant  Could you point me to the line number? I couldn't find any local overrides.

**Comment by ammohant** [comment]
I was going through mutiple actions to find such hard coding and came across the const.  Iam not finding it in this action . I will find the right action and raise it against the same. This issue we can close.
