### ISSUE TITLE
Instructions to generate the `creds` use deprecated CLI option '--sdk-auth'

### ISSUE THREAD

**Issue by phillipleblanc** [Azure/aks-set-context#40]
`az ad sp create-for-rbac --sdk-auth`
> Option '--sdk-auth' has been deprecated and will be removed in a future release.
> In a future release, this command will NOT create a 'Contributor' role assignment by default. If needed, use the --role argument > to explicitly create a role assignment.
> Creating 'Contributor' role assignment under scope '/subscriptions/[sub-id]'
> The output includes credentials that you must protect. Be sure that you do not include these credentials in your code or check  the credentials into your source control. For more information, see https://aka.ms/azadsp-cli
'name' property in the output is deprecated and will be removed in the future. Use 'appId' instead.

**Comment by erik-ha-msft** [comment]
Running into the same issue here. with --sdk-auth option vs without, the JSON keys are different (e.g. --sdk-auth gives clientId vs without, you get appId). 

Is it possible to update this workflow to use the new syntax? As phillipleblanc commented, the --sdk-auth flag will be deprecated.

As a temporary workaround without the --sdk-auth flag, I had to change and add keys in the JSON output, for example:

appId -> clientId
password -> clientSecret
tenant -> tenantId
add subscriptionId

```
{
  "clientId": "<redacted>",
  "displayName": "<redacted>",
  "name": "<redacted>",
  "clientSecret": "<redacted>",
  "tenantId": "<redacted>",
  "subscriptionId": "<redacted>"
}
```

Tested the changes in my own repository and managed to get it working.
