### ISSUE TITLE
README.md uses incorrect variable names

### ISSUE THREAD

**Issue by ncthbrt** [Azure/aks-set-context#5]
From the source code, `resourceGroupName` should actually be `resource-group`, 
while `clusterName` should actually be `cluster-name`

**Comment by benc-uk** [comment]
Just found the same :(

**Comment by ncthbrt** [comment]
Pinging @1ds-ms, who seems to be the main contributor to the this repo:  
This Github action is likely numbered one of the first that Azure Aks users evaluating Github actions is going to try out, at least it was for me, so it kind of feels like a bad look that the example given doesn't actually work.

**Comment by ds-ms** [comment]
Thanks for the PR. I missed updating the readme with some last minute changes we did. 

I've merged it. I'll update this in the marketplace as well.

**Comment by ncthbrt** [comment]
Thanks a lot!
