### ISSUE TITLE
Cannot get cluster admin credentials

### ISSUE THREAD

**Issue by ddran-averydennison** [Azure/aks-set-context#61]
in GA worlflow using that: 

  steps:
    - uses: azure/login@v1
      with:
        creds: ${{ inputs.aks_sp_secret }}

    - name: get AKS context
      id: dep_kube
      uses: azure/aks-set-context@v2.0
      with:
        cluster-name: ${{ inputs.cluster_name }}
        resource-group: ${{ inputs.resource_group }}
        admin: true

but as result receive: **Warning: Unexpected input(s) 'admin', valid inputs are ['resource-group', 'cluster-name']**

Done setting cloud: "azurecloud"
Login successful.
Warning: Unexpected input(s) 'admin', valid inputs are ['resource-group', 'cluster-name']

**Comment by OliverMKing** [comment]
This feature was added in v2.1. Please use that version.
