### ISSUE TITLE
use-kubelogin option does not work properly

### ISSUE THREAD

**Issue by illinar** [Azure/aks-set-context#66]
Setting `use-kubelogin` does indeed executes kubelogin, but it seems to modify wrong kubeconfig file.

```
Run azure/aks-set-context@v2.2
  with:
    cluster-name: xxx
    resource-group: xxx
    admin: false
    use-kubelogin: true
/usr/bin/az aks get-credentials --resource-group xxx --name xxx -f /home/runner/work/_temp/kubeconfig_1654654112792
WARNING: Merged "xxx" as current context in /home/runner/work/_temp/kubeconfig_1654654112792
/usr/local/bin/kubelogin convert-kubeconfig -l azurecli
```
Yet subsequent actions do not see updated kubeconfig. For instance,
```
Run azure/k8s-deploy@v3.1
Deploying manifests
/usr/local/bin/kubectl apply -f /tmp/baked-template-1654654116421.yaml --insecure-skip-tls-verify --namespace xxx
WARNING: the azure auth plugin is deprecated in v1.22+, unavailable in v1.25+; use https://github.com/Azure/kubelogin instead.
...
```

At the same time running `/usr/local/bin/kubelogin convert-kubeconfig -l azurecli` manually as a separate step _after_ aks-set-context has finished executing seems to work fine.

After looking at the source code I suspect the problem is that kubelogin is executed _before_ $KUBECONFIG environment variable has been exported. As such it does not "see" the right file to kubeloginify.

**Comment by illinar** [comment]
Thanks, but how can we test it without the released action?

**Comment by davidgamero** [comment]
releasing v2.3 now with the fix

**Comment by illinar** [comment]
Confirmed. v2.3 works.
